name: house-price-prediction
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  
  # Core packages
  - numpy=1.26.0
  - pandas=2.2.2
  - scipy=1.11.1
  - scikit-learn=1.3.0
  
  # ML Libraries
  - xgboost=1.7.5
  - lightgbm=4.1.0
  - catboost=1.2.2
  
  # Deep Learning
  - tensorflow=2.13.0
  - tensorflow-decision-forests=1.5.0
  
  # Optimization
  - optuna=3.3.0
  
  # Visualization
  - matplotlib=3.7.2
  - seaborn=0.12.2
  - plotly=5.15.0
  - jupyter=1.0.0
  - notebook=6.5.4
  
  # Install remaining via pip
  - pip:
    - ipywidgets==8.1.1
    - python-dateutil==2.8.2
    - pytz==2023.3
    